#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# detects that the battery should be replaced.
# We send an email message to root to notify him.
#

if [ -f /etc/apcupsd/email ]; then
  . /etc/apcupsd/email
fi

send_email "Battery needs changing NOW"

exit 0
