#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# restores contact with the UPS (i.e. the serial connection is restored).
# We send an email message to root to notify him.
#

if [ -f /etc/apcupsd/email ]; then
  . /etc/apcupsd/email
fi

send_email "Communications with UPS restored"

exit 0
