#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# We send an email message to root to notify him.
#

if [ -f /etc/apcupsd/email ]; then
  . /etc/apcupsd/email
fi

send_email "Power failure!"

exit 0
