#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# detects that the battery should be replaced.
# We send an email message to root to notify him.
#

if [ -f /etc/apcupsd/notify ]; then
  . /etc/apcupsd/notify
fi

notify "Battery needs changing NOW" 1

exit 0
