#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the    
# UPS goes back on to the mains after a power failure.
# We send an email message to root to notify him.
#

if [ -f /etc/apcupsd/notify ]; then
  . /etc/apcupsd/notify
fi

notify "Power has returned" 1

exit 0
