#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# We send an email message to root to notify him.
#

if [ -f /etc/apcupsd/notify ]; then
  . /etc/apcupsd/notify
fi

send_email "Power failure!" 1

exit 0
